#ifndef GAME_MACROS_H
#define GAME_MACROS_H

#define LIVING_PAC_HEIGHT 32
#define LIVING_PAC_WEIGHT 32
#define DEATH_PAC_HEIGHT 32
#define DEATH_PAC_WEIGHT 32
#define GHOST_HEIGHT 32
#define GHOST_WEIGHT 32
#define WALL_HEIGHT 7
#define WALL_WEIGHT 8

#endif // GAME_MACROS_H
