#ifndef GAME_MACROS_H
#define GAME_MACROS_H

#define LIVING_PAC_HEIGHT 32
#define LIVING_PAC_WEIGHT 32
#define DEATH_PAC_HEIGHT 32
#define DEATH_PAC_WEIGHT 32
#define GHOST_HEIGHT 32
#define GHOST_WEIGHT 32
#define WALL_HEIGHT 7
#define WALL_WEIGHT 8
#define SCORE_X 24
#define SCORE_Y 0
#define LIVES_X 24
#define LIVES_Y 400
#define MESSAGE_X 190
#define MESSAGE_Y 400

#endif // GAME_MACROS_H
